FROM python:3-focal

RUN apt-get update \
    && apt-get -y install rsync openssh-client \
    && rm -rf /var/lib/apt/lists/*

ARG USERNAME=builder
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && chown -R $USERNAME:$USERNAME /home/$USERNAME $HOME
USER $USERNAME
