name: buiild website pages

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GeoNetwork Website
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: sphinx install
        run: pip install --upgrade pip && pip install -r requirements.txt
      - name: build website pages
        run: |
          sphinx-build -a -b html docsrc target/website
